print("Generator CV")
imie_i_nazwisko = input("Podaj imię oraz nazwisko")
email = input("Podaj swój adres e-mail")
telefon = input("Podaj swój numer telefonu")
podsumowanie = input("Jednym zdaniem opisz swoje doświadczenie zawodowe")
umiejetnosc1 = input("Podaj 3 kluczowe umiejetnosci (kazda osobno)  (1)")
umiejetnosc2 = input("Podaj 3 kluczowe umiejetnosci (kazda osobno)  (2)")
umiejetnosc3 = input("Podaj 3 kluczowe umiejetnosci (kazda osobno)  (3)")
print(f"===============================\n CV: {imie_i_nazwisko}\n ===============================")
print(f"Kontakt:\n - E-mail: {email}\n - Telefon: {telefon}\n")
print(f"Podsumowanie:\n {podsumowanie}")
print(f"Umiejetnosci:\n - {umiejetnosc1}\n - {umiejetnosc2}\n - {umiejetnosc3}")
print("===============================")